version: '3'
dotenv:
  - ".env"
tasks:
  build:dev:
    desc: Build dev enviroment
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
      - docker container cp bin/apache/default.conf budgetcontrol-ms-name:/etc/apache2/sites-available/budgetcontrol.cloud.conf
      - docker container exec budgetcontrol-ms-name service apache2 restart
  run:db:
    desc: Run database
    cmds:
      - docker-compose -f docker-compose.db.yml up -d database
  run:cache:
    desc: Run database
    cmds:
      - docker-compose -f docker-compose.db.yml up -d database
  
  test:prepare:
    desc: Prepare test enviroment
    cmds:
      - docker container exec budgetcontrol-ms-goals bash -c "vendor/bin/phinx rollback -t0 && vendor/bin/phinx migrate && vendor/bin/phinx seed:run --seed=MainSeeds && vendor/bin/phinx seed:run --seed=GoalSeeds"
  test:run:
    desc: Run tests
    cmds:
      - docker container exec budgetcontrol-ms-goals bash -c "vendor/bin/phpunit --testdox --colors=always test"